### ISSUE TITLE
Leader election 

### ISSUE THREAD

**Issue by nalshamaajc** [aws/karpenter-provider-aws#4168]
### Description

**Observed Behavior**:
Randomly getting the below errors. The incident involved frequent deprovisioning and service outage noting that PDBs are set.
```
E0626 20:00:18.625437       1 leaderelection.go:367] Failed to update lock: Put "[https://172.20.0.1:443/apis/coordination.k8s.io/v1/namespaces/karpenter/leases/karpenter-leader-election](https://172.20.0.1/apis/coordination.k8s.io/v1/namespaces/karpenter/leases/karpenter-leader-election)": context deadline exceeded
E0626 19:38:37.928683       1 leaderelection.go:330] error retrieving resource lock karpenter/karpenter-leader-election: Get "[https://172.20.0.1:443/apis/coordination.k8s.io/v1/namespaces/karpenter/leases/karpenter-leader-election](https://172.20.0.1/apis/coordination.k8s.io/v1/namespaces/karpenter/leases/karpenter-leader-election)": net/http: TLS handshake timeout
E0626 19:35:58.115419       1 leaderelection.go:330] error retrieving resource lock karpenter/karpenter-leader-election: Get "[https://172.20.0.1:443/apis/coordination.k8s.io/v1/namespaces/karpenter/leases/karpenter-leader-election](https://172.20.0.1/apis/coordination.k8s.io/v1/namespaces/karpenter/leases/karpenter-leader-election)": http2: client connection lost
```
![Pasted Graphic 9](https://github.com/aws/karpenter/assets/114491638/1394e56b-1381-47bd-bd7d-19beaa2cbe26)

and another set of logs that are weird and are asking me to file a report

```
"level":"ERROR","time":"2023-06-29T14:15:21.662Z","logger":"controller.pod_state","message":"invariant violated registering host port usage, IP=0.0.0.0 Port=8125 Proto=UDP conflicts with existing HostPort configuration IP=0.0.0.0 Port=8125 Proto=UDP, please file an issue","commit":"d7e22b1-dirty","pod”:”xxxx/xxxx-djkh9"}

2
{"level":"ERROR","time":"2023-06-29T14:15:21.688Z","logger":"controller.pod_state","message":"invariant violated registering host port usage, IP=0.0.0.0 Port=8125 Proto=UDP conflicts with existing HostPort configuration IP=0.0.0.0 Port=8125 Proto=UDP, please file an issue","commit":"d7e22b1-dirty","pod”:”xxxx/xxxx-djkh9"}
```

Pods were restarting

![Pasted Graphic 5](https://github.com/aws/karpenter/assets/114491638/9af7c456-a930-43d9-96a9-04c4609abb7a)

We scaled the karpenter deployment to 4. Still seeing some weird logs.

- I see 2 logs which I'd like to know more about and how they might relate to the incident.
`failed to renew lease`
`client-side throttling`
![image](https://github.com/aws/karpenter/assets/114491638/5957c318-91d0-4ec7-9f26-26ce11bfeff6)

- Apparently this was the leader or trying to be.
What does panic mean in the logs and why was there so many timeouts. It shouldn't be normal to see that much errors right?
![image](https://github.com/aws/karpenter/assets/114491638/9277c396-ce48-4c9d-b724-840912bce4a2)

**Expected Behavior**:
Not getting these errors
**Reproduction Steps** (Please include YAML):
No clear steps so far
**Versions**: 
- Chart Version:  v0.27.3
- Kubernetes Version (`kubectl version`): v1.25.9-eks-5f89878
- Node OS Version: Bottlerocket OS 1.14.1 (aws-k8s-1.25)   5.15.108

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by jonathan-innis** [comment]
How much memory and cpu are you giving Karpenter? What kind of scale is your cluster running under? Typically we are seeing client-side throttling or logs like this when there are extremely large scale-ups or there are a lot of events on your cluster all happening at one time.

**Comment by nalshamaajc** [comment]
@jonathan-innis The resource limits were left as default (non set). In terms of scale we currently have 1394 pods which is everything on the cluster, 37 nodes managed by Karpenter, and 8 nodes for critical workloads (like Karpenter) that are under a Managed Node Group. Well in terms of events we are migrating some services to the cluster, but I don't think that was the case for the incident that is being addressed in this issue.

**Comment by shay-ul** [comment]
Hi @jonathan-innis, we are experiencing this as well:
```
2023-07-27T02:35:23.658Z	ERROR	controller	error retrieving resource lock karpenter/karpenter-leader-election: Get "https://172.20.0.1:443/apis/coordination.k8s.io/v1/namespaces/karpenter/leases/karpenter-leader-election": context deadline exceeded
	{"commit": "c3d4e73-dirty"}
```
We have a large cluster (scales up to over 700 nodes). I increased the Karpenter resource reuqests this is still happening.

```
          resources:
            requests:
              cpu: "2"
              memory: 2Gi
```

**Comment by roimor** [comment]
im having the same issue as above :(

**Comment by ellistarn** [comment]
Digging into this. @nalshamaajc, you absolutely should be setting cpu/memory, or you may get client side throttling. Given the other reports, I think there may be something going on with the EKS Control Plane. I'll raise this with the team. In the meantime, please submit a support ticket to EKS to diagnose these client timeouts.

**Comment by shay-ul** [comment]
HI @ellistarn , I have opened a support ticket - 13461296631. If you need any logs/details attached there, let us know.

**Comment by flavono123** [comment]
- Chart Version: v0.27.5
- Kubernetes Version (kubectl version): v1.24.16-eks-2d98532
- Node OS Version: AL2

having same issue on the above env, only about `failed to renew lease`. hope to solve soon

**Comment by jonathan-innis** [comment]
It may be worth trying out a `FlowSchema` here where the coordination APIs for Karpenter are prioritized so that the apiserver is less likely to drop leader election requests during periods of high traffic

```
apiVersion: flowcontrol.apiserver.k8s.io/v1beta3
kind: FlowSchema
metadata:
  name: karpenter-leader-election
spec:
  distinguisherMethod:
    type: ByUser
  matchingPrecedence: 300
  priorityLevelConfiguration:
    name: leader-election
  rules:
  - resourceRules:
    - apiGroups:
      - ""
      namespaces:
      - '*'
      resources:
      - endpoints
      - configmaps
      verbs:
      - get
      - create
      - update
    - apiGroups:
      - coordination.k8s.io
      namespaces:
      - '*'
      resources:
      - leases
      verbs:
      - get
      - create
      - update
    subjects:
    - kind: ServiceAccount
      serviceAccount:
        name: '*'
        namespace: karpenter
```

**Comment by jonathan-innis** [comment]
I think it might also make sense to assign the `workload-high` priority to _any_ request coming from the Karpenter controller as well

```yaml
apiVersion: flowcontrol.apiserver.k8s.io/v1beta3
kind: FlowSchema
metadata:
  name: karpenter-service-account
spec:
  distinguisherMethod:
    type: ByNamespace
  matchingPrecedence: 1000
  priorityLevelConfiguration:
    name: workload-high
  rules:
  - nonResourceRules:
    - nonResourceURLs:
      - '*'
      verbs:
      - '*'
    resourceRules:
    - apiGroups:
      - '*'
      clusterScope: true
      namespaces:
      - '*'
      resources:
      - '*'
      verbs:
      - '*'
    subjects:
    - kind: ServiceAccount
      serviceAccount:
        name: karpenter
        namespace: karpenter
```

**Comment by njtran** [comment]
@shay-ul, checking in here. Does any of the information above or given by the support ticket help out?

**Comment by sidewinder12s** [comment]
We actually got a crash/panic on Karpenter when leadership election failed. (When this happened it appeared the EKS Control Plane was going through some changes/issues that do not have me surprised that requests failed/had issues):

```log
{"level":"ERROR","time":"2023-09-29T21:04:52.458Z","logger":"controller","message":"Failed to update lock: Put \"https://172.20.0.1:443/apis/coordination.k8s.io/v1/namespaces/karpenter/leases/karpenter-leader-election\": context deadline exceeded\n","commit":"34d50bf-dirty"}
{"level":"INFO","time":"2023-09-29T21:04:52.458Z","logger":"controller","message":"failed to renew lease karpenter/karpenter-leader-election: timed out waiting for the condition\n","commit":"34d50bf-dirty"}
{"level":"INFO","time":"2023-09-29T21:04:52.458Z","logger":"controller","message":"Stopping and waiting for non leader election runnables","commit":"34d50bf-dirty"}
panic: leader election lost

goroutine 442 [running]:
github.com/samber/lo.must({0x1e2e580, 0x4010cb2d60}, {0x0, 0x0, 0x0})
        github.com/samber/lo@v1.38.1/errors.go:53 +0x1dc
github.com/samber/lo.Must0(...)
        github.com/samber/lo@v1.38.1/errors.go:72
github.com/aws/karpenter-core/pkg/operator.(*Operator).Start.func1()
        github.com/aws/karpenter-core@v0.29.2/pkg/operator/operator.go:170 +0x7c
created by github.com/aws/karpenter-core/pkg/operator.(*Operator).Start
        github.com/aws/karpenter-core@v0.29.2/pkg/operator/operator.go:168 +0xd0
```

**Comment by shay-ul** [comment]
@njtran we actually had no progress with that regards, unfortunately.
However, this is not Karpenter-related. The same thing also happens on all components which are implementing leader election using the Kubernetes API. On our use case, it also includes:

aws-load-balancer-controller
karpenter
keda-operator
ebs-csi-controller
efs-csi-controller

I believe this is the API Server unable to handle the load. We are continuing to investigate with AWS Support.

**Comment by shay-ul** [comment]
P.S the "API Priority and Fairness" (PriorityLevelConfiguration and FlowControl) solution for Karpenter may work and fix this issue for Karpenter, but to be honest - KEDA, ALB Controller, EBS and EFS CSI Controllers are also very important system components.
We would like to avoid entering this rabbit hole altogether. The fact that the control plane is caving under some pressure is disturbing, as EKS should support scale without the need to go through such customization. 

Is there a plan to add this FlowControl as a default to the helm chart, as in [this draft PR](https://github.com/aws/karpenter/pull/4530/files)?

thanks for the help!

**Comment by shay-ul** [comment]
Update on our case (13970038271):
The AWS Support team found evidence that during the time frames for this issue, etcd is going through "defragmentation" process due to large volume of the database. This process causes etcd to become read-only, blocking any write operations (for Karpenter - this means timeout for leader election).

Here are two articles on the matter:

https://aws.amazon.com/blogs/containers/explore-etcd-defragmentation-in-amazon-eks/
https://aws.amazon.com/blogs/containers/managing-etcd-database-size-on-amazon-eks-clusters/

needless to say, this is a **huge** problem, since this means EKS may be able to handle steady prefictable scale, but is unable to handle large auto scaling events.

**Comment by jonathan-innis** [comment]
> The fact that the control plane is caving under some pressure is disturbing

Agreed. We're still looking into the details onto the control-plane side to see what's causing the apiserver/etcd to just start throwing errors. We're also seeing this error on our test clusters as well. 

> Is there a plan to add this FlowControl as a default to the helm chart

As far as the FlowControl stuff goes, yes we want to get this in with the default helm chart, but I want to confirm through some more testing and discussing with some other SIGs that this is the right direction to go with how we think about our API Priority and Fairness.

**Comment by sidewinder12s** [comment]
> > The fact that the control plane is caving under some pressure is disturbing
> 
> Agreed. We're still looking into the details onto the control-plane side to see what's causing the apiserver/etcd to just start throwing errors. We're also seeing this error on our test clusters as well.
> 
> > Is there a plan to add this FlowControl as a default to the helm chart
> 
> As far as the FlowControl stuff goes, yes we want to get this in with the default helm chart, but I want to confirm through some more testing and discussing with some other SIGs that this is the right direction to go with how we think about our API Priority and Fairness.

I'd almost expect for flow control that karpenter should be able to just re-use one of the predefined FlowSchemas/PriorityLevelConfigurations for `leader-election` or `workload-high`

**Comment by sidewinder12s** [comment]
Makes sense to me, haven't really dug into either resource that heavily other than knowing they've been improving since 1.22.

**Comment by sidewinder12s** [comment]
We just hit this again. Should Karpenter really panic and crash when it is unable to hit the leader election endpoint? Or should it just backoff and retry? 

This ends up triggering paging alerts when karpenter crashes multiple times in a short period of time. Of note, we're on version 0.31 and have not migrated Karpenter to the kube-system namespace as now is recommended.

**Comment by cdenneen** [comment]
@jonathan-innis the helm-chart should be updated to supply these FlowSchemas are actually created if the namespace changes from `kube-system`

**Comment by jonathan-innis** [comment]
I'm going to close this out. As far as I know this is no longer an issue that occurs and we haven't seen this at all in our testing for a few months.

You can definitely still hit this issue if you get heavily throttled by the container CPU limits. Ensure that you give Karpenter enough requests so that it has enough CPU cycles to be able to refresh the leader election resource and you should be fine. Out of the box, Karpenter's default of 1 CPU should be enough to continually refresh this thread.

**Comment by korncola** [comment]
"as far as you know"?! its still an issue here and **I see no solution to this in this thread.**
We are just facing this issue.
