### ISSUE TITLE
Karpenter compatibility issue with EKS version 1.32

### ISSUE THREAD

**Issue by ssro** [aws/karpenter-provider-aws#7629]
### Description

**Observed Behavior**:
Karpenter helm release version 1.1.1

Karpenter throws a panic not being compatible with kubernetes 1.32

```
panic: validating kubernetes version, karpenter version is not compatible with K8s version 1.32

goroutine 1 [running]:
github.com/samber/lo.must({0x38c81e0, 0xc000b0a180}, {0x0, 0x0, 0x0})
	github.com/samber/lo@v1.47.0/errors.go:53 +0x1df
github.com/samber/lo.Must0(...)
	github.com/samber/lo@v1.47.0/errors.go:72
github.com/aws/karpenter-provider-aws/pkg/operator.NewOperator({0x42d15e0, 0xc0006b82d0}, 0xc00016f3c0)
	github.com/aws/karpenter-provider-aws/pkg/operator/operator.go:155 +0xf7c
main.main()
	github.com/aws/karpenter-provider-aws/cmd/controller/main.go:28 +0x2a
```

**Expected Behavior**:
Normal operation of karpenter

**Reproduction Steps** (Please include YAML):
Vanilla helm chart of karpenter deployed

**Versions**:
- Chart Version: 1.1.1
- Kubernetes Version (`kubectl version`):

Client Version: v1.32.1
Server Version: v1.32.0-eks-5ca49cb

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by younsl** [comment]
I also have the same version compatibility issue with karpenter v1.1.1 after upgrading EKS from v1.30 to v1.32. The issue occurs even if the worker nodes are on v1.30 while the control plane is on v1.32.

`karpenter` (v1.1.1) pod log:

```bash
panic: validating kubernetes version, karpenter version is not compatible with K8s version 1.32

goroutine 1 [running]:
github.com/samber/lo.must({0x3871320, 0xc000270240}, {0x0, 0x0, 0x0})
    github.com/samber/lo@v1.47.0/errors.go:53 +0x1df
github.com/samber/lo.Must0(...)
    github.com/samber/lo@v1.47.0/errors.go:72
github.com/aws/karpenter-provider-aws/pkg/operator.NewOperator({0x426f620, 0xc0006c8c30}, 0xc000516e00)
    github.com/aws/karpenter-provider-aws/pkg/operator/operator.go:155 +0xf7c
main.main()
    github.com/aws/karpenter-provider-aws/cmd/controller/main.go:28 +0x2a
```

**Comment by JoseAlvarezSonos** [comment]
We are seeing the same issues on our side after upgrading to 1.32

**Comment by JoseAlvarezSonos** [comment]
If anyone from the Karpenter side can provide an ETA would be amazing, just to kind of figure out if we can wait or if we need to recreate the cluster to downgrade the version (which we would like to avoid of course), thanks 🙏

**Comment by JoseAlvarezSonos** [comment]
Worth pointing out that this is the PR that should fix this issue: https://github.com/aws/karpenter-provider-aws/pull/7628

**Comment by jmdeal** [comment]
We've cut a [release](https://github.com/aws/karpenter-provider-aws/releases/tag/v1.1.2) which changes this to a soft failure, you can upgrade to v1.1.2 to unblock. I do want to emphasize that v1.1.x is still not considered compatible with k8s 1.32, I recommend referencing the [compatibility matrix](https://karpenter.sh/docs/upgrading/compatibility/#compatibility-matrix) before upgrading in the future.

**Comment by younsl** [comment]
I upgraded [karpenter container image](https://gallery.ecr.aws/karpenter/karpenter) from 1.1.1 to [1.1.2](https://github.com/aws/karpenter-provider-aws/releases/tag/v1.1.2). karpenter worked well with existing nodeclaim and ec2nodeclass resources, even without official compatibility. Karpenter also successfully replaced the old worker nodes running version 1.30 with the new version 1.32. Thanks all!

Here's a verified `karpenter` chart example:

```yaml
# charts/karpenter/values.yaml
controller:
  # -- Distinguishing container name (containerName: karpenter-controller).
  containerName: controller
  image:
    # -- Repository path to the controller image.
    repository: public.ecr.aws/karpenter/controller
    # -- Tag of the controller image.
    tag: 1.1.2
    # -- SHA256 digest of the controller image.
    digest: ~
```

**Comment by ssro** [comment]
@jmdeal 🙏 appreciate the swift response and action. The 1.1.2 version works well so far. My environment is a development cluster, perfect testing ground for this version

**Comment by GuguRD** [comment]
I am still facing the same problem with karpenter 1.1.2:

`panic: validating kubernetes version, karpenter version is not compatible with K8s version 1.32                                                                                                                                                                               
goroutine 1 [running]:
github.com/samber/lo.must({0x38c81e0, 0xc000944860}, {0x0, 0x0, 0x0})
    github.com/samber/lo@v1.47.0/errors.go:53 +0x1df
github.com/samber/lo.Must0(...)
    github.com/samber/lo@v1.47.0/errors.go:72                                                                                                                                                                                                                                 github.com/aws/karpenter-provider-aws/pkg/operator.NewOperator({0x42d15e0, 0xc0004bd0b0}, 0xc0003ef940)                                                                                                                                                                           github.com/aws/karpenter-provider-aws/pkg/operator/operator.go:155 +0xf7c                                                                                                                                                                                                 main.main()                                                                                                                                                                                                                                                                       github.com/aws/karpenter-provider-aws/cmd/controller/main.go:28 +0x2a  `

**Comment by booleanbetrayal** [comment]
Just hit this wall after upgrading all of our control planes successfully. There was no mention of this in the EKS upgrade guide, which there probably should be. Will there be a new release soon to support 1.32 officially? FWIW - EKS is already warning about EOL on 1.31.

**Comment by dshackith** [comment]
When using `1.1.2` we are still getting the same error on a new deploy. We are using `karpenter/controller:1.1.2@sha256:51bca600197c7c6e6e0838549664b2c12c3f8dd4b23744ab28202ae97ca5aed1` image and still seeing the following error when the pod runs on the node:
```
panic: validating kubernetes version, karpenter version is not compatible with K8s version 1.32                                                                                                                                                  

                                                                                                                                                                                                                                                  

 goroutine 1 [running]:                                                                                                                                                                                                                           

 github.com/samber/lo.must({0x3871320, 0xc0003198c0}, {0x0, 0x0, 0x0})                                                                                                                                                                            

     github.com/samber/lo@v1.47.0/errors.go:53 +0x1df                                                                                                                                                                                             

 github.com/samber/lo.Must0(...)                                                                                                                                                                                                                  

     github.com/samber/lo@v1.47.0/errors.go:72                                                                                                                                                                                                    

 github.com/aws/karpenter-provider-aws/pkg/operator.NewOperator({0x426f620, 0xc0006529c0}, 0xc000549580)                                                                                                                                          

     github.com/aws/karpenter-provider-aws/pkg/operator/operator.go:155 +0xf7c                                                                                                                                                                    

 main.main()                                                                                                                                                                                                                                      

     github.com/aws/karpenter-provider-aws/cmd/controller/main.go:28 +0x2a
```

**Comment by dshackith** [comment]
The issue above was due to using the incorrect sha256 value for the image.

**Comment by younsl** [comment]
If the problem is still there after you upgrade karpenter image tag to `1.1.2`, check the sha256 `digest` value again. In the karpenter chart's `values.yaml` file, you can set `.Values.controller.image.digest` to null by using `~`. Look at [this chart example](https://github.com/aws/karpenter-provider-aws/issues/7629#issuecomment-2613227314) for help.

**Comment by lifeofmoo** [comment]
Thank you!

I can't stress how underrated this comment is. It just got me out of a very tight pickle. I thought I'd been deploying/running version 1.2.1 on the controller for months, so was shocked to see this in the logs when I upgraded my staging eks cluster to v1.32 yesterday. 


This the was the hash I was using
`sha256:51bca600197c7c6e6e0838549664b2c12c3f8dd4b23744ab28202ae97ca5aed1` which I took from the latest 1.2.1 values.yaml docs at the time.
